apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocpvirt
  namespace: openshift-gitops
spec:
  destination:
    namespace: ocpvirt
    server: https://kubernetes.default.svc
  project: ocpvirt
  source:
    path: argocd
    repoURL: https://github.com/ValentinoUberti/webinar-ocpvirt.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
